### ISSUE TITLE
Fedora 25 / Gnome : don't seems to work

### ISSUE THREAD

**Issue by Shnoulle** [MaartenBaert/ssr#529] opened 2017-03-17 11:52 UTC
Hi, and thanks :)

I use Fedora 25 (4.9.13-201.fc25.x86_64) with ssr from rpmfusion-free

```
Nom         : simplescreenrecorder
Architectur : x86_64
Époque      : 0
Version     : 0.3.8
Révision    : 1.fc25
Taille      : 3.0 M
Dépôt       : @System
Depuis le d : rpmfusion-free
Résumé      : Simple Screen Recorder is a screen recorder for Linux
URL         : http://www.maartenbaert.be/simplescreenrecorder/
Licence     : GPLv3
Description : It is a screen recorder for Linux.
            : Despite the name, this program is actually quite complex.
            : It's 'simple' in the sense that it's easier to use than ffmpeg/avconv or VLC
```

Gnome version : Version 3.22.2 (on Wayland)

Graphic card: Intel® Bay Trail
```
00:02.0 VGA compatible controller [0300]: Intel Corporation Atom Processor Z36xxx/Z37xxx Series Graphics & Display [8086:0f31] (rev 0e) (prog-if 00 [VGA controller])
	Subsystem: Gigabyte Technology Co., Ltd Device [1458:1000]
	Flags: bus master, fast devsel, latency 0, IRQ 90
	Memory at d0000000 (32-bit, non-prefetchable) [size=4M]
	Memory at c0000000 (32-bit, prefetchable) [size=256M]
	I/O ports at f080 [size=8]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: i915
	Kernel modules: i915
```

But when i try to make a screencapture : seems i have only some ms for screen but get the mouse.

See http://shnoulle.net/IMG/mkv/record-2017-03-17_12.32.44.mkv 

I test too with same gnome on XORG : same issue.

[ffmpg](https://trac.ffmpeg.org/wiki/Capture/Desktop)  give near same, but [EasyScreenCast gnome extension](https://github.com/EasyScreenCast/EasyScreenCast) work very good.

**Comment by MaartenBaert** [comment] 2017-03-19 19:37
Duplicate of #431. SSR does not work on Wayland, because Wayland has no screen capturing API. GNOME can only record directly through the window manager by using a non-standard extension.

**Closed** 2017-03-19 19:37 UTC
Labels: duplicate
