### ISSUE TITLE
libgif codec is missing,

### ISSUE THREAD

**Issue by jeuxjeux20** [MaartenBaert/ssr#438] opened 2016-02-20 12:14 UTC
Hello,
I would like to record with SSR, the output would be a gif file.
I've already the libgif codec installed.
How to use this codec into SSR , or add it ?

**Comment by MaartenBaert** [comment] 2016-02-21 19:46
Duplicate of #196. SSR does not support GIF, the color space is too limited and the quality would be absolutely horrible (remember the days of '256 colors'?). Use WebM instead.

**Comment by iamgreaser** [comment] 2016-02-21 21:49
If you actually need to use gif, record it in the usual format then convert it to gif afterwards.

**Comment by jeuxjeux20** [comment] 2016-02-27 20:36
@MaartenBaert Yes, but making a gif for reddit about a game where colors and quality are literally not important  : [see Image](https://i.imgur.com/DIelxSX.png)


@iamgreaser i know, but i wanted to get a "lazy" method. It's taking me 5-10 minutes to find the correct size to upload, correct ratio, etc...

**Comment by MaartenBaert** [comment] 2016-02-28 13:58
5-10 minutes? It's just one command:
```
ffmpeg -i filename.mkv -ss <start> -t <length> -an -c:v gif filename.gif
```
This just copies the original video resolution, frame rate etc.

**Comment by jeuxjeux20** [comment] 2016-02-28 17:30
@MaartenBaert Yes, but the file is sometimes very big.

**Comment by iamgreaser** [comment] 2016-02-29 20:06
What, did you seriously expect that a format for lossless compression of 256-colour images would be more space-efficient than a video format?

If you're complaining about gifs being very big, you should probably just use webm.

In order to make gifs more palatable you need to convert them to a smaller physical size and use a smaller framerate. If you could actually be bothered spending more than 5 seconds converting it, you can use GIMP to optimise the gif (Filters -> Animation -> Optimise for GIF) and you'll get a smaller gif. You probably won't halve the size, though.

**Comment by jeuxjeux20** [comment] 2016-03-03 16:06
Okay i'll try.

**Comment by goobliata** [comment] 2016-10-30 03:52
I have a similar problem... the interface says putting the slider all the way to 0 ior h264 is lossless but it's not, thus the gifs when converted are very big. If there was true lossless recording, gif compression would be much higher on pixelated games like mine. So I guess I would like an actual way to record losslessly.

**Closed** 2016-10-30 09:01 UTC

**Comment by MaartenBaert** [comment] 2016-10-30 21:30
@goobliata libx264 with crf=0 IS lossless, except for the color space conversion, which can be disabled as explained [here](https://github.com/MaartenBaert/ssr/issues/502#issuecomment-254051540).

**Comment by goobliata** [comment] 2016-10-31 05:21
Thanks for the reply. I'm on Debian 8 and I don't have the libx264rgb codec, just libx264 (which doesn't give lossless results unless I'm doing something else wrong.) If I were to build ffmpeg with x264rgb, is there a way to force SSR to use it instead of the one that ships with Debian?

**Comment by MaartenBaert** [comment] 2016-11-01 00:27
Yes, you can make SSR load a different library using LD_LIBRARY_PATH. But before you do that, try regular libx264 with pixelformat=yuv444. It is extremely close to lossless already, the only remaining source of errors is the RGB-to-YUV conversion and this is limited to rounding errors. I still don't understand why you are trying to get perfect lossless results though.

**Comment by goobliata** [comment] 2016-11-01 05:32
I think there's a scaling issue, it looks as if the image is being scaled with a linear interpolation by 1 pixel or so... here's a screengrab of the output of SSR: http://gamblin.ca/ssr.png. This is usng huffyuv. Now when I record directly with avconv x11grab, I get true lossless output. I'm just hoping to get the same output with SSR's glinject (I tried the x11grab of SSR and I get the same scaled look.)

**Comment by MaartenBaert** [comment] 2016-11-03 22:06
Like I said, this is what you get with yuv420. Colors are downscaled by a factor 2. Switch to ```pixelformat=yuv444``` and it will be gone.

**Comment by goobliata** [comment] 2016-11-03 22:28
The colours are fine, that isn't the problem. I've tried yuv444 with the same results: there is scaling going on between pixels. As you can see the edges of each pixel is blended between the bordering pixel which is not lossless.

**Comment by goobliata** [comment] 2016-11-04 16:00
I think I may have found the reason for the non-lossless recordings. Seems to be a bug or "weird feature" of ffmpeg. Parameter order makes all the difference. If I use a command like:

```
ffmpeg -f alsa -i hw:3,1 -f x11grab -show_region 1 -y -r 60 -s 1280x720 -i :0.0+320,268 -c:v huffyuv -c:a pcm_s16le test.avi
```

I get a lossless recording. You can see when you run it that it's encoding with huffyuv and pcm_s16le. However if I do:

```
ffmpeg -f x11grab -show_region 1 -y -r 60 -s 1280x720 -i :0.0+320,268 -c:v huffyuv -f alsa -i hw:3,1 -c:a pcm_s16le test.avi
```

(for example) I get an MPEG4 (not lossless) with pcm_s16le audio. Seems as long as I leave -c:v and -c:a to the end, it works.

**Comment by MaartenBaert** [comment] 2016-11-06 01:44
Yes, the correct order is:
```
ffmpeg <inputoptions1> -i <input1> <inputoptions2> -i <input2> ... <codecoptions> <output>
```
Everything you put before the ```-i``` is considered an input option. Some options apply to both but have a different effect, for example ```-s``` as an input option will set the capture size, whereas ```-s``` as an output option will activate scaling.

**Comment by goobliata** [comment] 2016-11-06 01:52
Does this in any way apply to SSR? Because I still can't get lossless recording if for example I use huffyuv. I'm not sure how SSR works internally and whether it calls ffmpeg on the command line or not.

**Comment by MaartenBaert** [comment] 2016-11-06 02:08
In order to get lossless or near-lossless, you need two things:

- A codec that supports lossless or near-lossless.
- A pixel format that doesn't downsample the color channels.

SSR currently supports the following formats: NV12, YUV420P, YUV422P, YUV444P, BGRA, BGR24.
The following are good for lossless: YUV444P, BGRA, BGR24
Of those formats, libx264 supports: YUV444P, BGR24 (with libx264rgb)
Huffyuv does NOT support any of these, it supports only: YUV422P, RGB24, RGB32

The difference between RGB and BGR is very small (just a different order) but right now SSR doesn't contain code for RGB, only BGR. So it won't work with huffyuv.

So for now your best option is:

- libx264 with ```pixelformat=yuv444,crf=0``` as custom options.
- libx264rgb with ```pixelformat=bgr,crf=0``` as custom options.

Either of these options will fix all the color fringing you are seeing now.

**Comment by goobliata** [comment] 2016-11-06 02:26
OK, I've finally got it working. The final problem was just VLC doesn't save perfect screenshots :-/... when I rip the screens with ffmpeg they are lossless with the options you just gave.

Sorry for all the noise, and thanks for the patience. And also thanks for the great application!
