### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by jeffersoncarpenter** [MaartenBaert/ssr#444] opened 2016-03-17 15:32 UTC
On commit 2a64dfe there are errors in AVWrapper.cpp on lines 79, 80, and 106.  Looks like a value was turned into a pointer.

**Comment by freemanfromgodotengine** [comment] 2016-03-17 23:08
I can confirm that:

```
'`AV/FastResampler.cpp
../../src/AV/AVWrapper.cpp: In constructor ‘AVPacketWrapper::AVPacketWrapper()’:
../../src/AV/AVWrapper.cpp:79:11: error: request for member ‘data’ in ‘((AVPacketWrapper*)this)->AVPacketWrapper::m_packet’, which is of pointer type ‘AVPacket*’ (maybe you meant to use ‘->’ ?)
  m_packet.data = NULL;
           ^
../../src/AV/AVWrapper.cpp:80:11: error: request for member ‘size’ in ‘((AVPacketWrapper*)this)->AVPacketWrapper::m_packet’, which is of pointer type ‘AVPacket*’ (maybe you meant to use ‘->’ ?)
  m_packet.size = 0;
           ^
../../src/AV/AVWrapper.cpp: In destructor ‘AVPacketWrapper::~AVPacketWrapper()’:
../../src/AV/AVWrapper.cpp:106:27: error: cannot convert ‘AVPacket**’ to ‘AVPacket*’ for argument ‘1’ to ‘void av_free_packet(AVPacket*)’
   av_free_packet(&m_packet);
                           ^
Makefile:1250: recipe for target 'AV/simplescreenrecorder-AVWrapper.o' failed
make[2]: *** [AV/simplescreenrecorder-AVWrapper.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mv -f AV/.deps/simplescreenrecorder-FastResampler.Tpo AV/.deps/simplescreenrecorder-FastResampler.Po
```


Debian Testing 64-bit.

**Comment by jeffersoncarpenter** [comment] 2016-03-18 15:44
#445 I went ahead and fixed the compile errors in that file

**Comment by MaartenBaert** [comment] 2016-03-19 02:07
Merged. It didn't show up for me because I have the latest FFmpeg.

**Closed by MaartenBaert** 2016-03-19 02:07 UTC
