### ISSUE TITLE
Only cursor is recorded on Ubuntu 17.10 Wayland

### ISSUE THREAD

**Issue by corradoventu** [MaartenBaert/ssr#563] opened 2017-08-07 07:40 UTC
I installed SimpleScreenRecorder on Ubuntu 17.10 Wayland and when I try to record something only the cursor is recorded. If You need I may attach also the log but I don't know were it is.
[prova2.zip](https://github.com/MaartenBaert/ssr/files/1204149/prova2.zip)
corrado@corrado-HP-aa-0725:~$ inxi -GxxIS
System:    Host: corrado-HP-aa-0725 Kernel: 4.11.0-10-generic x86_64 (64 bit gcc: 6.3.0)
           Desktop: Gnome 3.24.3 (Gtk 3.22.17-0ubuntu1) dm: gdm3
           Distro: Ubuntu Artful Aardvark (development branch)
Graphics:  Card: Intel Haswell-ULT Integrated Graphics Controller
           bus-ID: 00:02.0 chip-ID: 8086:0a16
           Display Server: wayland (X.Org 1.19.3) driver: i915
           Resolution: 1366x768@59.80hz
           OpenGL: renderer: Mesa DRI Intel Haswell Mobile
           version: 4.5 Mesa 17.1.4 (compat-v: 3.0) Direct Render: Yes
corrado@corrado-HP-aa-0725:~$

**Comment by jreiners** [comment] 2017-08-08 16:34
Same issue on clean Fedora 26 install. I also cannot draw the rectangle region, on first click it goes back to the settings. I can get logs if you tell me where to look for them. I am also on wayland.

**Comment by Sunderland93** [comment] 2017-08-09 12:28
Wayland is not supported by SSR

**Comment by MaartenBaert** [comment] 2017-08-10 01:07
Duplicate of #431.

**Closed by MaartenBaert** 2017-08-10 01:07 UTC
