### ISSUE TITLE
Simple Screen REcorder only records sound

### ISSUE THREAD

**Issue by fredlecut** [MaartenBaert/ssr#648] opened 2018-04-13 17:01 UTC
I upgraded to Ubuntu 17:10 this week, and when I tried to record my screen, SSR only recorded the sound, Black screen.

**Comment by MaartenBaert** [comment] 2018-04-14 14:45
Duplicate of #431.

**Closed by MaartenBaert** 2018-04-14 14:45 UTC

**Comment by fredlecut** [comment] 2018-04-14 18:29
I went around by rebooting and starting an Xorg Ubuntu session
