### ISSUE TITLE
Synchronizer.cpp has no member named ‘channels’.

### ISSUE THREAD

**Issue by Geremia** [MaartenBaert/ssr#429] opened 2016-01-20 03:30 UTC
This is related to closed issue #363.

I get something similar with the most recent commit:

```Synchronizer.cpp: In the function ‘std::unique_ptr<AVFrameWrapper> CreateAudioFrame(unsigned int, unsigned int, unsigned int, unsigned int, AVSampleFormat)’:
AV/Output/Synchronizer.cpp:181:21: error: ‘AVFrame {aka struct AVFrame}’ has no member named ‘channels’
  frame->GetFrame()->channels = channels;```

**Comment by Geremia** [comment] 2016-02-11 23:30
I fixed this with a stop-gap patch:
```
diff --git a/src/AV/Output/AudioEncoder.cpp b/src/AV/Output/AudioEncoder.cpp
index 16b7342..d27d2b6 100644
--- a/src/AV/Output/AudioEncoder.cpp
+++ b/src/AV/Output/AudioEncoder.cpp
@@ -155,7 +155,7 @@ bool AudioEncoder::EncodeFrame(AVFrame* frame) {
                assert((unsigned int) frame->nb_samples == GetFrameSize());
 #endif
 #if SSR_USE_AVFRAME_CHANNELS
-               assert(frame->channels == GetStream()->codec->channels);
+               /*assert(frame->channels == GetStream()->codec->channels);*/
 #endif
 #if SSR_USE_AVFRAME_SAMPLE_RATE
                assert(frame->sample_rate == GetStream()->codec->sample_rate);
diff --git a/src/AV/Output/Synchronizer.cpp b/src/AV/Output/Synchronizer.cpp
index de6e7f8..2420222 100644
--- a/src/AV/Output/Synchronizer.cpp
+++ b/src/AV/Output/Synchronizer.cpp
@@ -178,7 +178,7 @@ static std::unique_ptr<AVFrameWrapper> CreateAudioFrame(unsigned int channels, u
        frame->GetFrame()->nb_samples = samples;
 #endif
 #if SSR_USE_AVFRAME_CHANNELS
-       frame->GetFrame()->channels = channels;
+       /*frame->GetFrame()->channels = channels;*/
 #endif
 #if SSR_USE_AVFRAME_SAMPLE_RATE
        frame->GetFrame()->sample_rate = sample_rate;
```

**Comment by MaartenBaert** [comment] 2016-02-22 00:13
Duplicate of #306, #363 (second part), #330, #201 and #195. Please, search before you open new issues.

If you compile on a distribution that uses avconv instead of ffmpeg, you need to configure with --disable-ffmpeg-versions (or use the simple-build-and-install script which detects this automatically).

**Closed by MaartenBaert** 2016-02-22 00:13 UTC
