### ISSUE TITLE
SSR records sound only with black screen

### ISSUE THREAD

**Issue by callmelord** [MaartenBaert/ssr#710] opened 2019-05-08 01:34 UTC
Hi
**The problem**
  after update the system(archlinux), SSR records video only with black screen.
**My System**
Operating System: Arch Linux
SSR-git from AUR
Desktop Environment: Gnome

**Comment by MaartenBaert** [comment] 2019-05-12 14:23
Duplicate of #431 ?

**Comment by callmelord** [comment] 2019-05-12 16:49
en, SSR do not support wayland

**Closed** 2019-05-14 09:32 UTC
