### ISSUE TITLE
Recording "box" when in selection mode.

### ISSUE THREAD

**Issue by richardfoley** [MaartenBaert/ssr#324] opened 2015-04-16 12:41 UTC
When using the rectangle selection or cursor-follow modes, there is no feedback as to what is being recorded. It would be nice to have an outline indicating the area being recorded. Perhaps this could switch on when the recording starts, and off again when it stops.

Otherwise - excellent and easy-to-use tool. [thumbs-up]

**Comment by StripedMonkey** [comment] 2015-04-16 14:51
I would have to check but I could have sworn that there was a outline that
you could see when you were editing the boundary, I however would find it
useful to see the boundary while recording.

**Comment by MaartenBaert** [comment] 2015-04-21 22:20
Duplicate of #199. Unfortunately I can't make the frame visible while recording without interfering with the recording itself (in many cases at least).

**Closed by MaartenBaert** 2015-04-21 22:20 UTC
Labels: duplicate

**Comment by richardfoley** [comment] 2015-04-23 15:30
The preview feature (on the last settings page) is useful to know about.

**Comment by StripedMonkey** [comment] 2015-04-23 18:55
True but its small, If you are trying to determine if the edge of something
with not a lot of contrast its kinda hard to tell
