### ISSUE TITLE
Weird colors in recorded video

### ISSUE THREAD

**Issue by ssv-170379** [MaartenBaert/ssr#360] opened 2015-08-29 15:40 UTC
(sorry for bad English) Video records and saves ok ( http://s21.postimg.org/x07bigndj/rec.png ) , but colors are messed up in saved file ( http://s21.postimg.org/z7bk6dsnr/play.png played on both Linux and Windows, other videos are ok). changed video encode formats with no luck.

Debian 8 x64 (testing branch, XFCE)
Nvidia blob 340.76

SimpleScreenRecorder 0.3.3
Compiled with GCC 4.9.3
Qt: header 4.8.7, lib 4.8.7
libavformat: header 56.36.100, lib 56.36.100
libavcodec: header 56.41.100, lib 56.41.100
libavutil: header 54.27.100, lib 54.27.100
libswscale: header 3.1.101, lib 3.1.101

**Comment by alu18999959g** [comment] 2015-08-30 05:33
Here occurs the same, only that in the stable version of Debian (Debian 8.1 Jessie).

![test mkv - smplayer_003](https://cloud.githubusercontent.com/assets/11272085/9565846/432f5820-4ee9-11e5-93e4-df54957d463a.png)


Steps to reproduce:

I try to install the two ways (i think):

A- The simplest way to compile.

$ sudo dpkg --add-architecture i386

$ sudo apt-get update

$ sudo apt-get install build-essential pkg-config qt4-qmake libqt4-dev libavformat-dev \
libavcodec-dev libavutil-dev libswscale-dev libasound2-dev libpulse-dev libjack-jackd2-dev \
libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxfixes-dev libxext-dev libxi-dev g++-multilib \
libx11-6 libxext6 libxfixes3 libxfixes3:i386 libglu1-mesa:i386

$ cd /usr/lib/i386-linux-gnu
$ sudo ln -s libGL.so.1 libGL.so
$ sudo ln -s libGLU.so.1 libGLU.so
$ sudo ln -s libX11.so.6 libX11.so
$ sudo ln -s libXext.so.6 libXext.so
$ sudo ln -s libXfixes.so.3 libXfixes.so
$ sudo ldconfig

$ ./simple-build-and-install

B- Compile step-by-step.

$ ./configure
$ make
$ sudo checkinstall (generate a .deb file)

$ apt-cache policy ssr

ssr:
  Installed: 2-1
  Candidate: 2-1
  Version table:
 *** 2-1 0
        100 /var/lib/dpkg/status

Regards

**Comment by MaartenBaert** [comment] 2015-09-04 17:26
Can you both send me the actual video file (a recording of a few seconds is enough), the SSR log file (~/.ssr/logs) or terminal output, and the graphics card type + driver that you are using?

Did you both compile from source? Is this a new problem, or did you just never try SSR before now?

**Comment by ssv-170379** [comment] 2015-09-05 07:15
My graphics card is Nvidia 660 GTX, driver version 340.76. I do not have ~/.ssr/logs. Only settings.conf and two empty folders (input-profiles and output-profiles) in ~./ssr/ Here's video file, console output (include videocard info) and settings.conf http://www.fileconvoy.com/dfl.php?id=ge0fa140f71e4f5c9999716180b1ed4041247fdcf7
I've compiled from sources (via ./simple-build-and-install). Previously used SSR on Fedora 21 on same hardware without any issues.

**Comment by alu18999959g** [comment] 2015-09-06 19:35
Sorry for the delay in answering, I realized ssr installing from source in Debian testing KDE and **NOT** weird colors anymore ..

**Note:** I deleted my partition where i had kde stable (Debian Jessie) and i have done the test in another partition where i have installed Debian Stretch (Testing).

**Logs**
https://mega.nz/#!blciyRqa!OCNWV4VHfytqv0Q1kb90FWZYD5k4JR43raqMExwmiGY

**Video**
https://mega.nz/#!C1VjhY4S!TPHQ6z6-77rfguGs97gv2_Sg7BFWu-wK950UFFB2RaQ

I think the developer **MaartenBaert** has introduced some changes on the source. 

Example:

When i run:

 ./simple-build-and-install

I remember something like delete old ssr ...

Regards

**Comment by ssv-170379** [comment] 2015-09-06 20:47
rm -rf ./ssr
git clone https://github.com/MaartenBaert/ssr
cd ssr
./simple-build-and-install

Colors are ok now. Consider closed.
**Thanks MaartenBaert!**

**Comment by MaartenBaert** [comment] 2015-11-01 23:08
Reopened because I've received multiple reports of this bug one day after the 0.3.4 release. The weird thing is that I can't reproduce this. One user screenshot shows that the preview is fine, which suggests that the problem is either the color space conversion or the video encoder itself (which was x264). Probably related to the new NV12 support, but I don't understand how this is happening.

**Comment by MaartenBaert** [comment] 2015-11-02 00:46
Found a way to reproduce it: compile from source with --disable-x86-asm and use pixel format YUV420. Looks like a bug in the non-SSE color space converter for YUV420. Ironically the new NV12 converter works fine, but the old one which wasn't supposed to change in any way is now broken.

**Comment by VosaXalo** [comment] 2015-11-03 19:38
Hi,
after the last update to the version 0.3.5 I have found a "strange" vertical bar on the right of the recorded video. Here a screenshot of a video that I have recorded yesterday (you can see the colored bar shown by the red arrows):

![screen](https://cloud.githubusercontent.com/assets/6298140/10919298/5bf93312-826a-11e5-9321-6e782cf96201.png)

**Comment by MaartenBaert** [comment] 2015-11-03 20:26
Fixed in 0.3.6 :).

**Comment by NikosEfthias** [comment] 2015-11-04 12:36
cannot build the latest under ubuntu  and still affected by the same problem though ffmpeg is installed on my pc when i say ./configure i get error  that says install ffmpeg or libav development package

**Closed** 2016-03-23 01:38 UTC
Labels: bug

**Comment by siduck** [comment] 2022-07-04 11:24
@MaartenBaert the recorded video here produces a bit dimmed colors than the original screen, is this normal?

![image](https://user-images.githubusercontent.com/59060246/177145126-2462c30a-6494-49d5-a687-184337686d2a.png)
