### ISSUE TITLE
respect xdg base directory specification

### ISSUE THREAD

**Issue by soloturn** [MaartenBaert/ssr#813] opened 2020-08-01 19:51 UTC
ssr should respect https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html xdg base directory specification when, instead of putting .ssr into the home directory.

**Comment by StripedMonkey** [comment] 2020-08-01 22:58
This is an exact Duplicate of #407
Personally speaking I agree, and would like it to be respected with the fallback of the .ssr directory/config. However, Maarten has stated pretty plainly that this is unlikely to happen.

**Comment by MaartenBaert** [comment] 2020-08-01 23:06
I also agree that it would have been better, the point is that I don't think the benefits outweigh the downsides at this point. Besides, SSR is hardly the only application that does this, looking at my own home folder it seems to be a 50/50 split between ~/.application and ~/.config/application.

**Closed by MaartenBaert** 2020-08-01 23:06 UTC

**Comment by MaartenBaert** [comment] 2020-08-01 23:41
I've now implemented a compromise: if the `~/.ssr` directory does not exist, but the `~/.config/simplescreenrecorder` directory does exist, then it will be used instead. In all other cases SSR will fall back to `~/.ssr`, creating it if necessary. So you can now move the SSR directory manually and keep your home folder (more) clean if you prefer.

**Comment by smac89** [comment] 2020-12-12 01:12
@MaartenBaert  I'm guessing this has not yet been released yet? I am on v0.4.2

**Comment by MaartenBaert** [comment] 2020-12-12 14:06
Correct - I will do another release, it's been a while and the code seems to be pretty stable now.

**Comment by smac89** [comment] 2021-01-24 21:59
Just here to comment that it works!
