### ISSUE TITLE
Recording From Multiple Devices Simultaneously

### ISSUE THREAD

**Issue by CountryfiedLinux** [MaartenBaert/ssr#375] opened 2015-10-02 18:38 UTC
I'd like to be able to record from my mic and sound card at the same time. It would be great for interviews, group discussion, etc.

**Comment by Strit** [comment] 2015-10-15 11:55
This would be an awesome built in feature. Right now you can do it with the commandline. See Maarten's page here: http://www.maartenbaert.be/simplescreenrecorder/recording-game-audio/

**Comment by OlsonB** [comment] 2015-11-02 12:38
It would be nice, like the feature in multiplatform OBS, to have an inbuilt mixer, showing the audio sources (microphones, sound card output) and be able to mix them on the fly with built in volume sliders - the preview there indicates the sound volume with a peak levels - http://imgur.com/a/p0wfx

**Comment by MaartenBaert** [comment] 2015-11-02 18:16
Duplicate of #67. It's on the todo list, but it's more work than it sounds and I have limited time.

**Closed by MaartenBaert** 2015-11-02 18:16 UTC
