### ISSUE TITLE
Black video

### ISSUE THREAD

**Issue by ItsWatterson** [MaartenBaert/ssr#664] opened 2018-06-19 01:39 UTC
Hi,

First, sorry for the wrong words in English ...

So I've always used SimpleScreenRecorder, but since the last update on my system the video is black.

Ubuntu Linux
Distribution Version: 17.10

I have no idea what the problem might be ...

**Comment by Username-with-no-name** [comment] 2018-06-21 15:53
Maybe Update again?

sudo apt-get update

**Comment by ItsWatterson** [comment] 2018-06-23 19:17
No, i try this...
The problem continues..

**Comment by MaartenBaert** [comment] 2018-06-24 17:55
Duplicate of #431. Switch to a non-Wayland session as described here:
http://www.maartenbaert.be/simplescreenrecorder/troubleshooting/#the-recording-is-completely-black-except-for-the-cursor

**Closed** 2018-06-24 17:55 UTC

**Comment by ItsWatterson** [comment] 2018-06-28 21:37
It worked! Thanks a lot!
