### ISSUE TITLE
No option for recording mono from one channel of a stereo microphone.

### ISSUE THREAD

**Issue by lsuess** [MaartenBaert/ssr#350] opened 2015-07-11 11:55 UTC
Needed if e.g. one channel does not work due to hardware reasons.

**Comment by MaartenBaert** [comment] 2015-07-16 19:54
Duplicate of #323. Your microphone isn't configured properly, this should be fixed at the ALSA/PulseAudio layer, not in SSR. #323 gives some workarounds.

**Closed by MaartenBaert** 2015-07-16 19:54 UTC
