### ISSUE TITLE
No video or preview

### ISSUE THREAD

**Issue by maxant** [MaartenBaert/ssr#556] opened 2017-07-23 10:53 UTC
Hello
Thanks for building a simple but feature complete screen recorder!
Unfortunately I cannot get the video capture to work. I have tried all different video formats, and my audio is recorded and plays back, but the playback screen is just black.
The preview is also black.
I have tried using different screen sizes, same problem.
The mouse pointer gets recorded, but everything behind it is black.
I have tried playback with VLC and mediaplayer.
Have you got any tips on how to work out what is wrong?
Cheers
Ant
PS Fedora 25, Gnome 3.22.2, AMD Cedar graphics, 64 bit OS, AMD Fx-6100 6 core cpu, 16GB ram
PPS same/similar problem with "recordmydesktop"

**Comment by QuImUfu** [comment] 2017-07-24 00:06
duplicate of #431

**Closed** 2017-07-27 22:29 UTC
Labels: duplicate

**Comment by maxant** [comment] 2017-08-25 21:13
installed ubuntu and now it works :-)
