### ISSUE TITLE
Video demo

### ISSUE THREAD

**Issue by hallergard** [MaartenBaert/ssr#325] opened 2015-04-20 06:37 UTC
Not an issue, but maybe of interest  https://youtu.be/VyXEBCp694I 
![summary](https://cloud.githubusercontent.com/assets/4476022/7224891/fac835be-e72f-11e4-8b0d-e4198c5eca37.jpg)

**Comment by MaartenBaert** [comment] 2015-04-21 21:59
Nice, but since this is not a bug or question I'm going to close this :).

**Closed by MaartenBaert** 2015-04-21 21:59 UTC
