### ISSUE TITLE
Compiling problem - ‘AVFrame’ has no member named ‘channels’

### ISSUE THREAD

**Issue by aurium** [MaartenBaert/ssr#330] opened 2015-05-05 03:48 UTC
At Debian Testing:
```
$ ./configure --prefix=/opt --without-jack
$ make
```
ends with:
```
g++ -DHAVE_CONFIG_H -I. -I..  -I./AV/Input -I./AV/Output -I./AV -I./common -I./GUI   -DQT_SHARED -I/usr/include/qt4 -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I/usr/include/qt4/QtCore  -DSSR_SYSTEM_DIR=\"/opt/share/simplescreenrecorder\"  -pthread -std=c++0x -g -O2 -MT AV/Output/simplescreenrecorder-AudioEncoder.o -MD -MP -MF AV/Output/.deps/simplescreenrecorder-AudioEncoder.Tpo -c -o AV/Output/simplescreenrecorder-AudioEncoder.o `test -f 'AV/Output/AudioEncoder.cpp' || echo './'`AV/Output/AudioEncoder.cpp
In file included from /usr/include/c++/4.9/cassert:43:0,
                 from ./Global.h:64,
                 from AV/Output/AudioEncoder.cpp:20:
AV/Output/AudioEncoder.cpp: In member function ‘virtual bool AudioEncoder::EncodeFrame(AVFrame*)’:
AV/Output/AudioEncoder.cpp:158:17: error: ‘AVFrame’ has no member named ‘channels’
   assert(frame->channels == GetStream()->codec->channels);
                 ^
Makefile:1134: recipe for target 'AV/Output/simplescreenrecorder-AudioEncoder.o' failed
make[2]: *** [AV/Output/simplescreenrecorder-AudioEncoder.o] Error 1
make[2]: Leaving directory '/tmp/ssr/src'
Makefile:432: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/ssr'
Makefile:364: recipe for target 'all' failed
make: *** [all] Error 2
```
Is this related to libav-tools package version? My version is 6:11.2-1

**Comment by MaartenBaert** [comment] 2015-05-07 23:41
Duplicate of #306. Short answer: configure with --disable-ffmpeg-versions.

**Closed by MaartenBaert** 2015-05-07 23:41 UTC
