### ISSUE TITLE
Allow recording audio from multiple sources

### ISSUE THREAD

**Issue by john01dav** [MaartenBaert/ssr#310] opened 2015-02-12 04:46 UTC
Hello! I would like to suggest that the ability to record audio from multiple sources (such as a webcam's microphone and system audio) is implemented. I tried using the various workarounds on the Internet however all of them are full of various issues. I remember that a Windows screen recorder I used to use when I used to use Windows had this feature and it made many things very easy. You can combine the audio streams on the fly or save them both and combine them at the end as the recording is saved.

**Comment by StripedMonkey** [comment] 2015-02-12 13:46
He's working on it, If you want to you can see a full list of planned
features in his todo list.
Right now the way SSR is set up it cannot receive multiple inputs so
currently its not possible.

**Comment by john01dav** [comment] 2015-02-12 20:47
In what way would this be? I am a programmer and perhaps I can come up with a solution. I'd look in the code myself, but I don't know C++ (I know other OOP languages though).

**Comment by StripedMonkey** [comment] 2015-02-12 21:14
This is Github, Look at the code yourself, I have no idea why its that way
however I do know from what little I know from keeping tabs on this project
that its just because it wasn't designed to. From what he (Maarten) has
said recently he is completely redoing the GUI so I expect that that is
going to be included in the GUI

**Comment by jamesmcm** [comment] 2015-02-15 14:12
Is there any way that we can just replay recorded audio back through the monitor via PulseAudio or something? Effectively merging the outputs at the pulseauido level.

**Comment by jamesmcm** [comment] 2015-02-15 14:18
Yep, this solution works for me: http://askubuntu.com/a/262297 (on Debian with PulseAudio at least)

Loopback the microphone through the monitor and then record from the monitor. You get a bit of added interference on the mic but it works alright.

**Comment by MaartenBaert** [comment] 2015-02-15 14:56
Yes. There's more information here:
http://www.maartenbaert.be/simplescreenrecorder/recording-game-audio/

The PulseAudio solution is buggy though. It may work fine for a few minutes but usually start to produce glitches if you use it too long. I don't recommend using it, especially for long videos.

**Comment by ubuntuaddicted** [comment] 2015-02-16 21:24
in my opinion pulseaudio has improved and i don't have as many issues as i used to when using the loopback method. i use ssr almost daily. ;)

**Comment by uniquejava** [comment] 2015-03-15 07:39
I'd like an option to record only the sound from my earphone(or system audio output may I say so?sorry for my bad English), So no background noises.  Many thanks. :)

**Comment by pelliott80** [comment] 2015-03-22 19:12
I believe this can be done if you are using pulse audio
with pulse volume control.


On Sun, Mar 15, 2015 at 12:39:11AM -0700, cyper wrote:
> I'd like an option to record only the sound from my earphone(or system audio output may I say so?sorry for my bad English), So no background noises.  Many thanks. :)
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/MaartenBaert/ssr/issues/310#issuecomment-80893879

-- 
Paul Elliott                               1(512)837-1096
pelliott@BlackPatchPanel.com               PMB 181, 11900 Metric Blvd Suite J
http://www.free.blackpatchpanel.com/pme/   Austin TX 78758-3117

**Comment by ubuntuaddicted** [comment] 2015-03-22 21:09
it's possible with loopbacks and a null sink. that's how I do it. there's an easy way and a difficult way. both are here: http://www.maartenbaert.be/simplescreenrecorder/recording-game-audio/

**Comment by Ape** [comment] 2015-05-05 08:22
This is a duplicate of #67. This is a wonderful project, but the issue tracker needs some cleaning.

**Closed** 2015-11-02 18:16 UTC
